### PR TITLE
Change circle.yml to follow svcops best practices

### PR DESCRIPTION
**Pull request by robotblake**

### CODE REVIEW

**Comment by mreid-moz** [comment]
This looks fine to me. @purukaushik what do you think?

**Comment by maurodoglio** [comment]
Hey @robotblake can you also remove the existing version.json file please?

**Comment by maurodoglio** [comment]
lgtm

**Comment by purukaushik** [comment]
There is a test case that looks for version.json(testing the `/__version__` endpoint). So we should probably have one at first.

**Pull request merged**
